### ISSUE TITLE
Additional FOMs

### ISSUE THREAD

**Issue by jo-moeller** [European-XFEL/EXtra-foam#117]
Please add standard deviation (nanstd(I)), variance (nanvar(I)) and normalized variance (nanvar(I)/nanmean(I)**2) to the possible ROI FOMs.

Cheers, Johannes

**Comment by zhujun98** [comment]
This is straightforward. I would say `normalized variance` is a temporary option for ROI FOM since after pulse-resolved normalization is implemented, one can achieve it by applying a normalizer.

**Comment by jo-moeller** [comment]
Thanks. Normalized variance is still something different though, as you normalize on the square of the mean intensity in your ROI. -> nanvar(I)/nanmean(I)**2, with I being the array of pixel intensities in the ROI.
This is actually the most important of the three options for us, as this is equal to the speckle contrast.

**Comment by zhujun98** [comment]
I did not read the equation carefully. What you need is the square of normalized standard deviation. I just googled and the normalized standard deviation is also called speckle contrast by some people.
Anyway, I think it makes sense to make `normalized variance` a special ROI FOM.

**Comment by zhujun98** [comment]
I  assume you will not need to use it recently. If yes, let me know and I will make it available on the test (`alpha`) version. Otherwise, the new release 0.8.2 will come in the 30th of this month.
