### ISSUE TITLE
Move control widgets of statistics analysis to their own window

### ISSUE THREAD

**Issue by zhujun98** [European-XFEL/EXtra-foam#120]
As I am planning to add more options for the statistics analysis, i.e. binning, correlation and histogram, it is not convenient for the control panels to stay in the main GUI. So the plan is to move them to their respective plot windows. @ebadkamil 

I already received strong "criticism" from Jola :-), @jo-moeller, I heard you also would like to have this change.

**Comment by jo-moeller** [comment]
I am not sure how this would look like in the end, but I don't have a strong opinion on this :)
But a certain rearrangement probably makes sense.
