### ISSUE TITLE
Transition to GitHub Workflows

### ISSUE THREAD

**Issue by RobertRosca** [European-XFEL/EXtra-foam#288]
With the recent changes to Travis we plan on moving most EuXFEL repositories to GitHub Workflows for testing. We've also put through an order for our own DA server and plan to deploy runners onto that so that we can have more powerful hardware and more storage access for tests.

Does that sound good to you @zhujun98? I can change the CI myself, or would you prefer to do it?

**Comment by zhujun98** [comment]
Sure! Please go ahead.
