### ISSUE TITLE
Combine JungFrau detector in EXtra-foam

### ISSUE THREAD

**Issue by daviddoji** [European-XFEL/EXtra-foam#298]
Hi @zhujun98.

There is already a flag (`n_modules 2`) to be passed when starting EXtra-foam with JungFrau detectors that assembles two modules into a single image. If one uses that flag, it can only look at the `append` image for two JF modules and not at a single module or for example, the smaller JF500k. To visualize these, one has to start EF without any flags.

In karabo, there is already a "combine" image doing the assembly for the JFs, but when using that device, EF throws errors, no matter if we use the flag or not. Errors are different when using or not the flag, but both are related to the shape EF expects. For LPD, it's the same story. EF accepts the `append` image, but not the `combine` from karabo.

Is there already something implemented to deal with those "combined" images? Especially for JFs, it would be really useful, as one only would have to instantiate EF once and would be able to visualize both, the single module (JF500k) and the combination of both.

Cheers,
David

**Comment by zhujun98** [comment]
`EXtra-foam` can assemble JungFrau modules with a geometry and it strictly checks the input data shapes. It does not like the stacked image from other sources since the geometry information is required for certain analysis. For example, other instruments already use 8 JungFrau modules together.

> one only would have to instantiate EF once and would be able to visualize both, the single module (JF500k) and the combination of both.

One cannot visualize both at the same time. You probably mean switching between them. In this case, one can simply launch two instances or visualize another one with special suite as a general camera image.

**Comment by daviddoji** [comment]
Thx for the clarification @zhujun98. I'll go then with the special suite.

Regarding visualization, perhaps I didn't express myself clearly. In theory one could visualize both at the same time because they are independent detectors (JF500K and JF1M which has two modules, JF1M_module1 and JF1M_module2)

P.S.: Feel free to close the issue ;)

**Comment by ebadkamil** [comment]
> Regarding visualization, perhaps I didn't express myself clearly. In theory one could visualize both at the same time because they are independent detectors (JF500K and JF1M which has two modules, JF1M_module1 and JF1M_module2)

EXtra-foam will get data from the last device of the calibration process. In case of JF1M, the last device is an appender which sends out data from two modules together (matches with there trainIDs) and therefore with `-n 2` as command line argument you get an assembled image in EXtra-foam. 
 
Two independent detectors need two independent EXtra-foam instances running.

**Comment by daviddoji** [comment]
Thx for the clarification @ebadkamil :)

**Comment by zhujun98** [comment]
> Regarding visualization, perhaps I didn't express myself clearly. ...

It is me who did not express myself clearly :-). By visualizing at the same time, I mean "at the same time in one instance"
